### ISSUE TITLE
Miscellaneous issues

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#12]
### Tasks
- [x] `libyt` unknown message `[DEBUG]`
- [ ] ~Code units and CGS units are mixed when plotting derived fields~

**Comment by cindytsai** [comment]
Second task should move to #3 , as they basically are the same.

**Comment by hyschive** [comment]
@cindytsai Feel free to correct it directly :)

**Comment by cindytsai** [comment]
The second is not caused by `libyt`
