### ISSUE TITLE
Add Timer for Performance Test

### ISSUE THREAD

**Issue by cindytsai** [calab-ntu/libyt#50]
# Add Timer for Performance Test

## Section
- [x] Loading parameter: adding python variable from Python C++ API.
- [x] Wrapping grids to NumPy array.
- [x] Executing inline script
- [x] Getting data from derived fields.
- [x] Data transition in RMA operation (One-Sided MPI)
- [x] Clean up.

## Links
- A really ugly timer at `cindytsai/yt` branch `libyt-timer`: [link](https://github.com/cindytsai/yt/tree/libyt-timer)
- To use timer in `libyt`, see: [link](https://github.com/calab-ntu/libyt/pull/51)

**Comment by hyschive** [comment]
@cindytsai You could consider utilizing the built-in [timer](https://github.com/gamer-project/gamer/blob/master/include/Timer.h) in GAMER.

**Comment by cindytsai** [comment]
@hyschive I just built a light-weight one.
