### ISSUE TITLE
Rename the default branch from master to main

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#69]
[Reference](https://github.com/github/renaming#renaming-existing-branches)

**Comment by cindytsai** [comment]
@hyschive I don't have the permission to change the default branch.

**Comment by hyschive** [comment]
@cindytsai I just noticed that there is already a `main` branch. I'll need to delete it first and then rename `master` as `main`. Is that OK for you?

**Comment by cindytsai** [comment]
@hyschive I merging my PR to that main branch. So maybe after I merge it? (Actually, I created that because I cannot rename default branch)

**Comment by hyschive** [comment]
@cindytsai OK. Let me know when it's ready.

**Comment by cindytsai** [comment]
@hyschive You can delete `master` branch now.

**Comment by hyschive** [comment]
@cindytsai Just to be sure. What I'll do is to delete the current `main` branch and then rename `master` as `main`. If you agree, please merge the current `main` into `master` first.

**Comment by cindytsai** [comment]
@hyschive Can we just delete `master`? (I'm not sure if we can do that.)

**Comment by hyschive** [comment]
We better follow the official [guideline](https://github.com/github/renaming#renaming-existing-branches).

**Comment by hyschive** [comment]
@cindytsai So I prefer deleting `main` and then renaming `master`.

**Comment by hyschive** [comment]
@cindytsai I still see two branches [here](https://github.com/calab-ntu/libyt/branches) and `master` is still the default branch. Have you followed the official instructions?

**Comment by cindytsai** [comment]
@hyschive I don't have the permission to do that. I can't change default branch's name.

![Screenshot from 2023-02-09 21-33-09](https://user-images.githubusercontent.com/6188366/217994124-6abcb081-a733-4b0a-b828-0c65126e2824.png)
